# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Yuewen Zhang
first_name: Yuewen
middle_name: 
last_name: Zhang
email: z15000675672@gmail.com
contact_note: >
  Looking for Ph.D. opportunities (Fall 2026).
description: >
  HPC Engineer @ Insta360 | M.Sc. from UCAS
footer_text: >
  Copyright © 2025 Yuewen Zhang. Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: Computer Vision, Domain Generalization, VLM, MLLMs
lang: en
icon: ⚛️

url: "https://ywzhang1031.github.io"
baseurl: ""  

# -----------------------------------------------------------------------------
# Theme & Layout
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: false

navbar_fixed: true
footer_fixed: true
search_enabled: false
bib_search: false

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Jekyll Scholar (让你的名字在论文列表中加粗)
# -----------------------------------------------------------------------------
scholar:
  last_name: [Zhang]
  first_name: [Yuewen, Y.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: none
  group_order: descending

# -----------------------------------------------------------------------------
# Other Settings
# -----------------------------------------------------------------------------
enable_publication_badges:
  google_scholar: true
  altmetric: false
  dimensions: false

enable_publication_thumbnails: true
enable_math: true
enable_darkmode: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
include: ["_pages", "_scripts"]
exclude: ["bin", "Gemfile", "Gemfile.lock", "vendor", "node_modules", "README.md", "LICENSE"]
keep_files: ["CNAME", ".nojekyll"]
plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
sass:
  style: compressed
jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js"]
terser:
  compress:
    drop_console: true
